shakacode/react-webpack-rails-tutorial

README.md

Currently links to: https://github.com/justin808/react-webpack-rails-tutorial/blob/master when you click the demo app link

Fix link to demo app

---

Gemfile
Gemfile.lock

See attached image for the warning:
https://cloudup.com/cZzMtRGE5oU

"scss-lint" has been renamed to "scss_lint"

---

CHANGELOG.md
README.md
app/views/layouts/application.html.erb
client/package.json
client/webpack.hot.config.js
package.json

Author in both package.jsons is still justin808, wasn't sure there.  But the rest seem important.

more justin808 -> shakacode conversions

---

client/.jscsrc
client/assets/javascripts/actions/CommentActionCreators.js
client/assets/javascripts/utils/CommentsManager.js
client/package.json
client/webpack.common.config.js

Use fetch instead of $.ajax

---

README.md

It's surprising to click a URL and end up at a different URL.

Make localhost links in README clickable

---

README.md

The error shown if Postgres is missing is confusing—for me it was along the lines of:
```
Installing pg 0.18.2 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
/Users/user/.rbenv/versions/2.2.2/bin/ruby -r ./siteconf20150907-78059-f9x8cq.rb extconf.rb
checking for pg_config... no
No pg_config... trying anyway. If building fails, please try again with
--with-pg-config=/path/to/pg_config
checking for libpq-fe.h... no
Can't find the 'libpq-fe.h header
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
```
To save the next person some time, I suggest we add the "check" to the docs.

Added hint to check that Postgres is installed

---

Gemfile
Gemfile.lock
README.md
app/assets/javascripts/application.js
client/npm-shrinkwrap.json
client/package.json
client/scripts/rails_only.jsx
client/webpack.common.config.js
client/webpack.rails.config.js

Comment out jquery-rails gem
Remove require for jQuery and jQuery-ujs from application.js
Change required order of application.js client-bundle and es5-shim
Add jquery-ujs to package.json and npm shrinkwrap
Remove comments about jQuery from webpack.common.config.js
Remove jQuery loader expose from webpack.rails.config.js
Comment out jQuery import or external jQuery since it is served from
/client.
Move jQuery and jQuery-ujs expose to via require to rails_only.jsx entry point.
Add info to README about using jQuery with Rails and Webpack
This fixes #51

Move jQuery and jQuery-ujs under /client and npm

---

.coveralls.yml
.gitignore
Gemfile
Gemfile.lock
README.md
spec/rails_helper.rb

Add Coveralls.io gem "coveralls" to implement code coverage monitoring
Add status badges to README for Codeship ans Travis-CI builds, Coveralls code-coverage, and Gemansium gem dependency monitoring and security.

Code coverage and badges

---

README.md

No need to work hard installing capybara-webkit when it was removed by 07950bd08f63c

Remove an unneeded section from the README

---

client/npm-shrinkwrap.json
client/package.json

Bump up npm module jquery-ujs to latest release 1.1.0-1.
npm shrinkwrap due to module update.

Update npm module jquery-ujs to 1.1.0-1, npm shrinkwrap

---

README.md

There was a `www` at the top, which with the subdomain `forum` leads to a `ERR_NAME_NOT_RESOLVED`

Fix forum URL

---

.gitignore
.travis.yml
Gemfile
Gemfile.lock
Procfile.dev
app/views/pages/index.html.erb
client/assets/javascripts/ClientApp.jsx
client/assets/javascripts/ServerApp.jsx
client/assets/javascripts/actions/CommentActionCreators.js
client/assets/javascripts/clientGlobals.jsx
client/assets/javascripts/serverGlobals.jsx
client/assets/javascripts/utils/CommentsManager.js
client/npm-shrinkwrap.json
client/package.json
client/scripts/webpack_only.jsx
client/webpack.common.config.js
client/webpack.hot.config.js
client/webpack.rails.config.js
client/webpack.server.config.js
config/initializers/assets.rb
config/initializers/react_on_rails.rb
lib/tasks/assets.rake
spec/features/comments_spec.rb
spec/rails_helper.rb

Add server-bundle.js to .gitignore
Add server webpack command to Procfile.dev
Create webpack.server.config.js for server side rendering.
Add react_on_rails config initializer file
Rename App.jsx to ServerApp.jsx to use for App server-side
Add clientGlobals.jsx entry point for client-side rendering
Add serverGlobals.jsx entry point for server-side rendering
Add ClientApp.jsx for client-side App
Take the existing setup and add server-side rendering.

Bump react_on_rails gem version to 1.0.3

---

Gemfile
Gemfile.lock
lib/tasks/ci.rake

* Run brakeman like:
`brakeman --exit-on-warn --quiet -A`
* This makes ci fail if there's a brakeman issue.
* Updated brakeman gem to current (3.1.1)
* Bonus: Added pry debugging gems

Updated ci.rake usage of brakeman

---

README.md

Upadate README

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
scripts/lint

Add require react_on_rails to application.js

update react_on_rails gem to latest 0.1.8

---

README.md
app/controllers/pages_controller.rb
app/views/comments/_comment.json.jbuilder
app/views/comments/index.json.jbuilder
app/views/comments/show.json.jbuilder
app/views/pages/index.html.erb

* Change to use the same JSON for the server side load and the client
side load of the comments.
* Reuse one jbuilder template for the list and single view of comments.
* Update the docs with how to do this.

Unify use of jbuilder with server rendering

---

client/package.json
client/webpack.client.hot.config.js
client/webpack.server.rails.config.js

Add NODE_ENV variable to server build & Switch to react-transform-hmr

---

spec/rails_helper.rb

Fix capybara screenshot render during failing tests by assigning the custom js driver.
Add capybara default_wait_time per Travis CI common build errors: 
http://docs.travis-ci.com/user/common-build-problems/#Capybara%3A-I%E2%80%99m-getting-errors-about-elements-not-being-found

Ci build issues

---

client/app/components/CommentForm.jsx
client/app/components/CommentList.jsx
client/app/startup/ClientApp.jsx
client/app/startup/ServerApp.jsx
client/index.jade
client/webpack.client.base.config.js

- New required propTypes for `ReactCSSTransitionGroup`
- Provider component doesn't need to wrap a function anymore
- The `render` method now belongs to the `ReactDOM` lib

Fix warnings of upgrading to React 0.14

---

Gemfile
Gemfile.lock
client/README.md
client/webpack.server.rails.config.js

Have to expose ReactDOMServer as well for the server rendering per 0.14 upgrade docs.

We need this as well for proper 0.14 server support.

---

Procfile.dev
README.md
client/server.js
client/webpack.client.hot.config.js
spec/requests/server_render_check_spec.rb

This fixes #116.
- Change Rails server port to default (3000).
- Change Webpack dev server port to 4000.
- Add simple server rendering tests

Reverse ports of Webpack and Rails server

---

db/migrate/20151015160035_set_default_for_author_and_text.rb
db/migrate/20151015160334_change_author_and_text_to_not_null.rb
db/schema.rb

The last parameter of `change_column_null` only affects existing records, thus the new default value still needed to be set by `change_column_default`.
Fixes #110.

Set comment's author and text as not null and defaults as empty string

---

lib/tasks/assets.rake

Ensure that users copying example files won't run into issues due to references to `RailsReactTutorial::Application`, which obviously won't be the name of their app. Instead, use `Rails.application`. This reflects similar changes in https://github.com/shakacode/react_on_rails/pull/53
Besides the actual `config/application.rb` file and the `<title>` element of the main layout, I found no other occurrences.

Change calls of ReactOnRails to Rails.application

---

Gemfile
Gemfile.lock

No longer necessary as we are relying on Webpack to use its own es5-shim loader.
Thanks to @hisapy: https://github.com/shakacode/react-webpack-rails-tutorial/pull/131#issuecomment-152184021

Remove es5-shim from Gemfile

---

Gemfile
Gemfile.lock
config/database.yml

Also, add comment to database.yml

updates for readability

---

client/app/utils/metaTagsManager.js
client/npm-shrinkwrap.json
client/package.json

Add lodash as discussed in #124.

Add lodash and update dependencies

---

client/.eslintrc
client/app/components/Comment.jsx
client/app/components/CommentBox.jsx
client/app/components/CommentForm.jsx
client/app/components/CommentList.jsx
client/app/components/CommentScreen.jsx
client/app/components/SimpleCommentScreen.jsx
client/app/reducers/commentsReducer.js
client/app/startup/ClientApp.jsx
client/app/startup/ServerApp.jsx
client/app/stores/commentsStore.js
client/webpack.client.base.config.js

I also cleaned up all the trailing commas (that where everywhere) because they are lint etc issues (rubymine in particular really dislikes them). They hurt nothing to take out.
@justin808 After submitting a comment, which works, there is still an issue (that seems like) a "this.props" where this isn't defined.
You'll notice in the PR various uses of .bind(this).. that is because ES6 react classes don't automagically do that anymore (so like, a clickHandler method cannot refer to "this" (which they all do) unless you do this._handleClick.bind(this) sort of syntax)
Clearly I missed one/haven't unraveled it yet :)  That being said, this has to be 95-99% there and this way more eyes can get on it.

ES6 all React stuff.

---

.travis.yml
client/.eslintrc
client/app/stores/commentsStore.js

@justin808, @robwise, @alexfedoseev  
I was able to fix the failing Travis CI build with setting Travis to install package `g++-4.9`.
However, I fixed the failing Codeship build by setting `react/prop-types: 0` within `.eslintrc`. 
This was the build fail issue:
And referenced here in the issues for `eslint-plugin-react`: 
https://github.com/yannickcr/eslint-plugin-react/issues/9
I am sure you will not want to have this rule continually ignored; therefore, someone will need to address the issue in the code?
Thanks,
Dylan

Fix ci build failures

---

client/app/bundles/Comments/store/commentsStore.js
client/package.json

The package `eslint-plugin-react` was updated to fix this issue: https://github.com/yannickcr/eslint-plugin-react/issues/345#event-483515053
So now we can re-enable the eslint rule that was crashing our `commentStore`. (see #168 and #166).

Update package eslint-plugin-react to fix bug

---

client/app/bundles/Comments/startup/serverGlobals.jsx
client/npm-shrinkwrap.json
client/package.json
client/webpack.client.base.config.js
client/webpack.client.hot.config.js
client/webpack.client.rails.config.js
client/webpack.server.rails.config.js

jquery-ujs is not needed for the Webpack Dev Server setup.

Del jquery-ujs from webpack.client.base.config.js

---

spec/rails_helper.rb

- Loads CSS from running server. Useful when debugging feature tests
with `save_and_open_page`.

Adds Capybara.asset_host

---

client/app/libs/metaTagsManager.js

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/209)

fix lodash find syntax to return correct csrf-token content

---

client/app/bundles/comments/layout/Layout.jsx

`Layout.jsx` should extend `BaseComponent` both to take advantage of the `PureRenderMixin` and to maintain consistency with the other components used in the example.
Resolves issue shakacode/react-webpack-rails-tutorial#211
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/214)

Update Layout to extend BaseComponent. 

---

Procfile.dev
Procfile.spec
Procfile.static
package.json

Basically we just don't need the special `build:test:client` script anymore, and you can just use `Procfile.static` to keep your static assets up to date while running your tests.
Also changed the ordering of the scripts so that the client and server versions of the same type of script are next to each other.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/216)

Fix Procfiles to use new process names

---

lib/tasks/assets.rake

The rake asset compilation task will now run the production-specific npm build scripts, which employ the `UglifyJsPlugin` plugin.
There may be reasons I'm not aware of to *not* do this, but this is what I would assume would happen for a production build, which is generally what you're targeting when running asset precompilation.
The numbers below just approximately sum vendor and app bundles.
current `bin/rake assets:precompile` (total approx 6.1 MB)
explicitly running npm prod builds in `bin/rake assets:precompile` (total approx 2.3 MB)
explicitly running npm prod builds in `bin/rake assets:precompile` AND adding minification plugin (total approx 600 KB)
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on …

Minify js in production.

---

client/package.json

Those are dependencies of eslint-config-shakacode, so including them
creates a chance of a version conflict.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/243)

Remove babel-eslint and eslint-config-airbnb

---

.gitignore
CHANGELOG.md
Gemfile
Gemfile.lock
README.md
app/views/comments/index.json.jbuilder
client/app/bundles/comments/actions/commentsActionCreators.js
client/app/bundles/comments/components/SimpleCommentScreen/SimpleCommentScreen.jsx
client/app/bundles/comments/store/commentsStore.js
client/app/bundles/comments/store/routerCommentsStore.js
config/database.yml
config/initializers/react_on_rails.rb
docs/contributors.md
spec/rails_helper.rb
spec/spec_helper.rb
spec/support/phantomjs-disable-animations.js

Updated props to have comments top level prop of comments.
Now, the server responds:
{ comments: [ c1, c2, etc.] }
Before the props were just:
[c1, c2, etc.]

Fix comments json format

---

app/assets/stylesheets/application_static.scss

This logic is handled by /config/initializers/assets.rb
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/255)

Remove unnecessary erb suffix

---

README.md

On a fresh install on OSX, `capybara-webkit` will fail to build.
```sh
Installing capybara-webkit 1.8.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
[..]
Command 'qmake' not available
```
`capybara-webkit` is required only by the Gemfile's test group, so one option is to simply exclude that test group when installing.
I think a better option is to provide instructions for how to get `qmake` installed. The actual commands required on OSX are:
```sh
brew tap homebrew/versions
brew install qt55
brew link --force qt55
```
But since those might change, and vary for other operating systems, I recommend linking to the `capybara-webkit` install docs directly in the README.
---
This change is [<img src="https://reviewable.io/review_button.svg" …

Update README with instructions for installing qmake

---

spec/rails_helper.rb

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/268)

fix lint and require issues causing 'bin/rake ci' to fail

---

app/controllers/application_controller.rb

Disable CSRF for json requests to enable mobile requests to the API
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/306)

Disable csrf for json

---

client/npm-shrinkwrap.json
client/package.json
client/webpack.client.base.config.js
package.json

By setting the vendor libs as entry points, we force the vendor code
into the vendor-bundle.js. This has the advantage in that app code
should be changing less often, so client browsers will have the vendor
bundle cached longer, and the smaller app bundle can be refreshed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/307)

Make the vendor bundle hold vendor code

---

Procfile.dev
Procfile.express
README.md
client/app/bundles/comments/startup/ClientRouterAppExpress.jsx
client/index.pug
client/package.json
client/server-express.js
client/webpack.client.express.config.js

Fixes to reenable express server rendering.
* Had to work around no shared store support
* https://github.com/shakacode/react_on_rails/issues/504
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/313)

Express server rendering

---

client/app/bundles/comments/actions/commentsActionCreators.js
client/app/bundles/comments/components/CommentBox/CommentForm/CommentForm.jsx
client/app/bundles/comments/components/SimpleCommentScreen/SimpleCommentScreen.jsx
spec/features/add_new_comment_spec.rb
spec/features/shared/examples.rb

Partially resolves #295
`Simple React` page.
I probably will try to fix other pages as well.
(Later. When I feel myself less sick.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/321)

Show errors on the "Simple React" page.

---

.travis.yml
Gemfile
README.md
docs/integration-test-notes.md
spec/factories.rb
spec/features/destroy_comment_spec.rb
spec/rails_helper.rb
spec/support/poltergeist.rb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/345)

remove the require for chromedriver

---

README.md
config/cable.yml
config/environments/production.rb

See article
https://blog.heroku.com/real_time_rails_implementing_websockets_in_rails_5_with_action_cable
This fix requires this command to be run:
```
heroku config:set PRODUCTION_HOST=www.reactrails.com  --app react-webpack-rails-tutorial
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/360)

Change configuration for ActionCable

---

spec/rails_helper.rb

* Previously only flagging feature specs.
* This ensures that webpack does its thing before any tests under
/spec/features or /spec/requests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/375)

Test helper now flags request specs

---

Gemfile
Gemfile.lock
client/package.json
client/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/388)

Update to React on Rails v7.0.0

---

Procfile.dev
Procfile.hot
Procfile.static

as discussed here: https://github.com/shakacode/react-webpack-rails-tutorial/pull/395 this ENV variable was changed with the move to react_on_rails 8 and webpacker lite.
@justin808
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/401)

update ENV variable for react_on_rails 8

---

README.md

The old repo doesn't exist anymore, so I think replacing it with the original source makes sense here. Worked fine with my heroku deployment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/400)

Removed and replaced no longer available repo

---

Gemfile
Gemfile.lock
client/package.json
client/yarn.lock
config/initializers/react_on_rails.rb
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/438)

Upgrade ReactOnRails to 11.0.3

---

client/.eslintrc.yml
client/app/bundles/comments/components/CommentBox/CommentList/Comment/Comment.spec.jsx
client/app/bundles/comments/components/CommentBox/CommentList/CommentList.spec.jsx
client/app/libs/testHelper.js
client/app/libs/testNullCompiler.js
client/package.json
client/yarn.lock
docs/tests-and-ci.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/445)

#444 Migrate JS tests to Jest

---

Gemfile.lock

Deployment to heroku was failing due to nokogori dependency issue:
```
remote: -----> Using Ruby version: ruby-3.1.2
remote:        Purging Cache. Changing stack from cedar-14 to heroku-22
remote: -----> Installing dependencies using bundler 2.3.25
remote:        Running: BUNDLE_WITHOUT='development:test' BUNDLE_PATH=vendor/bundle BUNDLE_BIN=vendor/bundle/bin BUNDLE_DEPLOYMENT=1 bundle install -j4
remote:        Fetching gem metadata from https://rubygems.org/.........
remote:        nokogiri-1.12.5-x86_64-linux requires ruby version < 3.1.dev, >= 2.5, which is
remote:        incompatible with the current version, 3.1.2
remote:        Bundler Output: Fetching gem metadata from https://rubygems.org/.........
remote:        nokogiri-1.12.5-x86_64-linux requires ruby version < 3.1.dev, >= …
```

updated nokogori gem to enable deployment to heroku

---

config/webpack/commonWebpackConfig.js
config/webpack/webpack.config.js

As per [this PR on React_on_Rails](https://github.com/shakacode/react_on_rails/pull/1460/), we can safely ignore warning related to requiring `react-dom/client` in React <18.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/519)

Ignore warning for react-dom/client not found

---

app/views/pages/_header.html.erb

The link to "The React on Rails Doctrine" article was the old one. It is updated to the new link at https://www.shakacode.com/blog/the-react-on-rails-doctrine/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/531)

Update the link to ROR doctrine

---

client/app/bundles/comments/components/CommentBox/CommentList/Comment/Comment.jsx
package.json
yarn.lock

Because the sanitize option in marked is deprecated and not safe This commit replace it with sanitize-html which works well with Server Side Rendering unlike DOMPurify.
Resolves #500
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/535)

Replace marked sanitize with sanitize-html (#500)

---

.github/workflows/js_test.yml
.github/workflows/lint_test.yml
.github/workflows/rspec_test.yml
package.json

- Replace `xvfb-action` with `coactions/setup-xvfb`
- Clean up workflows
closes #537
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/544)

Update Github Actions for CI

---

Gemfile
Gemfile.lock
bin/dev
bin/dev-static
package.json
yarn.lock

Add standard react_on_rails binstubs (`bin/dev` and `bin/dev-static`) for running the server.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/554)

Add ror binstubs

---

Gemfile
Gemfile.lock

After upgrading Rails to v7.1, it is necessary to upgrade Redis to v4+.
This PR fixes the issue of submitting comments and broadcasting them to all active sessions. It doesn't resolve the errors related to deleting comments in the Classic Rails tab.
---
Closes #558 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/561)

Upgrade redis to v4

---

.controlplane/readme.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/562)

Update cpln deployment docs

---

app/helpers/pages_helper.rb
spec/system/pages_spec.rb

This is to follow the same convention of using commit hash so that in one glance we can detect if we are the desired commit or not.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/566)

Show first seven char of commit hash

---

app/views/pages/rescript.html.erb
client/app/bundles/comments/rescript/ReScriptShow.res
client/app/bundles/comments/rescript/bindings/ActionCable.res

Adding ActionCable to the Rescript page to receive the new broadcasted comments. see the [js example](https://github.com/shakacode/react-webpack-rails-tutorial/blob/764a299e7e7e5f0643523d1aa691fcb7a87d4f99/client/app/bundles/comments/components/CommentBox/CommentBox.jsx#L35C7-L35C7)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/570)

Add ActionCable to rescript (#565)

---

.controlplane/readme.md

There was a step in the wrong order to try to execute cli `cpln` even before it is installed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/575)

Fix the instruction was in a wrong order.

---

.github/workflows/deploy-to-control-plane.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/577)

Deploy on merge to master

---

lib/tasks/ci.rake
spec/rails_helper.rb
spec/rescript/rescript_spec.rb
spec/stimulus/turbo_spec.rb
spec/system/add_new_comment_spec.rb
spec/system/react_router_demo_spec.rb

The changes in `rescript_spec.rb` and `turbo_spec.rb` improve our test accuracy.
~The changes in `spec/system/*` fix the test failure when these tests run before others (leading to their failure).~
~I am not sure why we have tests in the `system` directory that should have the type of `feature`, but it fixes our issues. I need to study deeper to understand what is happening under the hood.~
~Should I move these `feature` tests into the `feature` directory, or we can keep them this way for now?~
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/581)

Improve tests result consistency

---

db/schema.rb

This is a missing change from our past upgrade to Rails 7.1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/582)

Update `db/schema` for Rails 7.1

---

.controlplane/Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/588)

Update Dockerfile for more efficiency

---

.controlplane/controlplane.yml
.github/workflows/promote-staging-to-production.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/630)

Fix Promotion Workflow

---

.github/workflows/deploy-to-control-plane-review-app.yml
.github/workflows/deploy-to-control-plane-staging.yml
.github/workflows/review-app-help.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/642)

Another PR to test Github Actions Workflows

---

.github/workflows/promote-staging-to-production.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/647)

Add Timestamp to Release Tag
