shakacode/react-webpack-rails-tutorial

client/assets/javascripts/components/Comment.jsx
client/assets/javascripts/components/CommentBox.jsx
lib/tasks/daily.rake
spec/features/comments_spec.rb
spec/rails_helper.rb

1. Markdown is github flavored and sanitized
2. Some help text explaining that text is treated as markdown
3. Rake task to delete tasks older than 24 hours

Several slight enhancements, most importantly sanitization

---

client/assets/javascripts/actions/CommentActionCreators.js
client/assets/javascripts/components/CommentBox.jsx
client/assets/javascripts/components/CommentForm.jsx
client/assets/javascripts/components/CommentList.jsx
client/assets/javascripts/components/CommentScreen.jsx
client/assets/stylesheets/_app-styling-post-bootstrap-loading.scss

* Fix bug preventing ajax loader from working
* Reset the comment form only upon success
* Display errors on the comment form and comment list if communication with the server fails

Address some outstanding issues with Alt -> Flux migration

---

Gemfile
Gemfile.lock
client/assets/javascripts/actions/CommentActionCreators.js
client/assets/javascripts/components/CommentBox.jsx
client/assets/javascripts/components/CommentForm.jsx
client/assets/javascripts/components/CommentList.jsx
client/assets/javascripts/components/CommentScreen.jsx
client/assets/stylesheets/_app-styling-post-bootstrap-loading.scss
spec/features/comments_spec.rb

- Reset form upon each submit
- Ajax process indicator fix
- Added gem "phantomjs" (useful if not installed locally)
- Fixed test suite and refactored

Fixed some issues

---

client/.jscsrc
client/assets/javascripts/actions/CommentActionCreators.js
client/assets/javascripts/utils/CommentsManager.js
client/package.json
client/webpack.common.config.js

Reverts shakacode/react-webpack-rails-tutorial#73

Revert "Use fetch instead of $.ajax"

---

Gemfile
Gemfile.lock
app/views/pages/index.html.erb
client/assets/javascripts/App.jsx
client/index.html
client/webpack.common.config.js
client/webpack.hot.config.js
client/webpack.rails.config.js

@samnang @mapreal19 I just added a commit to make the hot reload server work again.
Did either of you try with http://localhost:3000?
@alexfedoseev How's this look?

react on rails gem setup

---

.travis.yml

Create travis.yml file to verify working build process on CI platform.

Add travis.yml file for Travis-CI build

---

Gemfile
Gemfile.lock
config/initializers/react_on_rails.rb

Add server side default config to initializers/react_on_rails.rb

Update react_on_rails gem to latest version 1.0.7

---

client/npm-shrinkwrap.json
client/package.json

Resolve #111 by upgrading react-bootstrap@0.25.2 to 0.26.4. This resolved the confirmed exception in rendering error.
NPM shrinkwrap

Upgrade react-bootstrap module to 0.26.4 and npm shrinkwrap

---

.gitignore
app/assets/javascripts/application.js
app/controllers/pages_controller.rb
app/views/comments/_form.html.erb
app/views/comments/show.html.erb
app/views/layouts/application.html.erb
app/views/pages/index.html.erb
app/views/pages/simple.html.erb
client/app/components/CommentBox.jsx
client/app/components/CommentForm.jsx
client/app/components/CommentList.jsx
client/app/components/SimpleCommentScreen.jsx
client/app/startup/clientGlobals.jsx
client/app/utils/commentsManager.js
client/app/utils/metaTagsManager.js
config/routes.rb
spec/features/comments_spec.rb

@josiasds Here is the code we worked on.  Let's see if we can finish getting this working asyncronously

WIP - simple comment form example

---

config/application.rb
config/initializers/assets.rb

config.assets.paths << Rails.root.join("client", "assets", "stylesheets")

Trying out all the assets configuration diff spot

---

app/assets/javascripts/application.js
app/assets/javascripts/rails_startup.js

As described [here](https://github.com/shakacode/react-webpack-rails-tutorial/commit/d677265c6410fb481241c9cd114bf7dfff2dcef1?diff=unified#commitcomment-14116053).
/cc @justin808

Move JS code from application.js

---

client/app/components/CommentList.jsx
client/npm-shrinkwrap.json
client/package.json
client/server.js

enable react animations for comments list

---

app/controllers/comments_controller.rb
app/controllers/pages_controller.rb
client/app/bundles/comments/components/CommentBox/CommentList/CommentList.jsx
client/app/bundles/comments/components/CommentBox/CommentList/CommentList.spec.jsx
client/app/bundles/comments/components/SimpleCommentScreen/SimpleCommentScreen.jsx
client/app/bundles/comments/reducers/commentsReducer.js
client/npm-shrinkwrap.json

Setting ID DESC order on server, disable reorder on client

---

spec/rails_helper.rb

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/210)

Port 3000 on Capybara.asset_host

---

Gemfile
Gemfile.lock
app/assets/javascripts/rails_startup.js
client/npm-shrinkwrap.json
client/package.json

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/229)

Turbolinks 5 and React on Rails v3.0.0-RC.2

---

README.md

Added Turbolinks 5 and url to repository under the ‘Technologies involved’ section.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/230)

Add Turbolinks 5 To README

---

client/.eslintrc.yml
client/package.json

Fixes #228
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/233)

Add eslint-shakacode-config

---

client/app/bundles/comments/startup/ServerRouterApp.jsx

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/235)

Fix broken link

---

Procfile.hot
Procfile.static
app/assets/javascripts/application_static.js.erb
app/assets/stylesheets/application_static.scss
app/assets/stylesheets/application_static.scss.erb
app/views/layouts/application.html.erb
client/webpack.client.base.config.js
client/webpack.client.rails.hot.config.js
docs/jquery-with-react-on-rails.md

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/244)

Fixed up the Procfile.static and Procfile.hot

---

Gemfile
Gemfile.lock
Procfile.dev
Procfile.hot
Procfile.static
Procfile.static.trace
README.md
app/assets/stylesheets/application_non_webpack.scss
app/helpers/application_helper.rb
app/views/layouts/application.html.erb
app/views/pages/no_router.html.erb
client/npm-shrinkwrap.json
client/package.json
config/initializers/react_on_rails.rb
config/routes.rb
spec/features/add_new_comment_spec.rb
spec/features/shared/contexts.rb
spec/rails_helper.rb
spec/support/driver_registration.rb

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/249)

Update v4 react on rails

---

app/assets/javascripts/application_static.js
config/initializers/assets.rb

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/253)

Make assets.rb cleaner

---

Gemfile
Gemfile.lock
client/app/bundles/comments/startup/ServerRouterApp.jsx
client/npm-shrinkwrap.json
client/package.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/260)

Update to 5.0.0.rc.1 of ReactOnRails

---

client/webpack.client.rails.hot.config.js

See discussion:
https://github.com/shakacode/react-webpack-rails-tutorial/issues/245
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/267)

Enable hot reloading

---

Gemfile
Gemfile.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/273)

Need listen gem for Rails 5

---

client/app/bundles/comments/reducers/index.js
client/app/bundles/comments/store/commentsStore.js
client/app/bundles/comments/store/routerCommentsStore.js

Fixes a mispelling: initalStates -> initalStates
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/278)

Fix mispelling

---

package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/280)

Fixed missing parenthesis in package.json

---

README.md

The subject in the sentence is in plural form.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/282)

some minor grammar correction

---

client/app/bundles/comments/startup/ServerRouterApp.jsx

Previously not set correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/286)

Fixed the setting of the location react-router

---

Gemfile
Gemfile.lock
client/npm-shrinkwrap.json
client/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/290)

Updated to React on Rails v6

---

Procfile.dev
Procfile.hot
README.md

Hi Justin! 
This was PR #285, I squashed the commits, added the line you suggested to Procfile.hot, and rebased this commit on top of current state of master branch.
Apologies, I simply misunderstood the other time & merged instead of rebasing.
I hope it's ok now.
Thank you
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/291)

Fixing references among procfiles & in README

---

app/views/pages/_header.html.erb

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/292)

Fix broken link to blog post

---

Gemfile
Gemfile.lock
app/views/pages/index.html.erb
client/npm-shrinkwrap.json
client/package.json

Had to manually set the DOM ID on the react component call in order to
fix a broken test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/293)

Update to 6.0.2

---

.buildpacks
README.md

Using heroku recommendations by setting the buildpacks at the command
line.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/303)

Change from .buildpacks file

---

Gemfile
Gemfile.lock

This will make server rendering faster.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/312)

Switch to mini_racer

---

README.md

Updated from therubyracer to mini_racer #309
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/311)

updated from therubyracer to mini_racer

---

client/server-rails-hot.js

As the code is now, it ignores the local variable that can be set from any environment variables
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/326)

Update dev server command to use rails port variable

---

app/views/pages/_header.html.erb
app/views/pages/index.html.erb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/330)

update static content

---

Gemfile.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/338)

Update mini-racer for Mac OS Sierra

---

app.json
client/package.json

https://github.com/yarnpkg/yarn/issues/1981#issuecomment-295429678
Error is:
```
remote:        ERROR in ./~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/style-loader!./~/css-loader!./~/resolve-url-loader!./~/sass-loader/lib/loader.js?sourceMap!./~/bootstrap-loader/lib/bootstrap.styles.loader.js?{"bootstrapVersion":3,"preBootstrapCustomizations":"/tmp/build_e3c98d01f5e715149d520a99d1ca219a/client/app/assets/styles/bootstrap-pre-customizations.scss","extractStyles":true,"styleLoaders":["style","css","sass"],"styles":["mixins","normalize","print","glyphicons","scaffolding","type","code","grid","tables","forms","buttons","component-animations","dropdowns","button-groups","input-groups","navs","navbar","breadcrumbs","pagination","pager","labels","badges","jumbotron","thum …
```

Add app.json, mod client/package.json for node-sass deploy

---

Gemfile
Gemfile.lock
spec/rails_helper.rb
spec/support/poltergeist.rb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/397)

Update testing gems

---

Gemfile
Gemfile.lock
client/package.json
client/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/410)

Update to 8.0.6

---

Gemfile
Gemfile.lock
client/package.json
client/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/440)

Bump ReactOnRails to 11.0.7

---

client/app/bundles/comments/components/NavigationBar/NavigationBar.jsx
client/app/bundles/comments/constants/paths.js
client/app/bundles/comments/layout/Layout.jsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/448)

#413 nav-bar consistency fixed

---

.controlplane/Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/508)

Patches to Sergey's Control Plane Branch

---

Gemfile
Gemfile.lock
config/initializers/react_on_rails.rb
package.json
yarn.lock

updated dependencies and build_production_command configuration
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/510)

updated dependencies and build_production_command configuration

---

README.md

To make cpln docs more discoverable, mentioned those on the main page.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/512)

added mentions of the cpl documentation on the mainpage

---

.controlplane/controlplane.yml
.controlplane/readme.md
Gemfile
Gemfile.lock
README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/521)

Doc Updates for Control Plane

---

client/README.md
docs/linters.md

The `client/bin` does not exist.  This PR update all its related links and updates the `client/README.md` link.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/540)

Update docs (#538)

---

app/views/layouts/application.html.erb

A simple improvement in HTML head meta tags to make the app look proper on small screens.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/551)

Improve HTML responsiveness

---

README.md
app/views/pages/_header.html.erb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/560)

Remove react-native reference

---

app/views/pages/_header.html.erb

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/564)

Add reference to Control Plane in header

---

.controlplane/Dockerfile

This step is needed for deploying the project on ControlPlane.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/568)

Add rescript build command in dockerfile

---

lib/tasks/daily.rake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/571)

Log daily task result directly in terminal

---

Gemfile
Gemfile.lock
package.json
yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/580)

Bump Shakapacker from 7.1.0 to 7.2.1

---

Gemfile
Gemfile.lock
package.json
yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/589)

Bump react_on_rails to v14

---

.github/workflows/add-comment-on-pr-creation.yml
.github/workflows/deploy-to-control-plane-review.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/600)

[chore], [fix] Use latest github-script v7, fix: typo in adding gh comments

---

.github/workflows/deploy-to-control-plane-review.yml

This effectively undoes a bug caused by a bad suggestion from coderabbit
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/602)

[FIX]: issue_comment gh actions event not checking out the correct branch

---

.github/workflows/deploy-to-control-plane-review-app.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/628)

Require comment trigger for Review Apps

---

.github/workflows/deploy-to-control-plane-staging.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/629)

Replace reference to deploy bash script with direct command
